# Generated by Django 5.2.13 on 2026-04-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0002_referral"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="confirmation_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
