# Generated by Django 5.2.13 on 2026-04-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0003_appointment_confirmation_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
