# Generated by Django 5.2.13 on 2026-04-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0004_alter_appointment_end_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="confirmation_sent",
            field=models.BooleanField(default=False),
        ),
    ]
