# Generated by Django 5.2.13 on 2026-04-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0005_appointment_confirmation_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmenttype",
            name="duration_minutes",
            field=models.IntegerField(default=30),
        ),
    ]
