# Generated by Django 5.2.13 on 2026-04-24 13:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0006_alter_appointmenttype_duration_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="appointment",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Clinical/session notes for this appointment.",
                null=True,
            ),
        ),
    ]
